 export const GET_PLAYERS_REQUEST = "GET_PLAYERS_REQUEST";
 export const GET_PLAYERS_SUCCESS = "GET_PLAYERS_SUCCESS";
 export const GET_PLAYERS_FAILURE = "GET_PLAYERS_FAILURE";

 export const GET_PLAYERS_REQUESTBYID = "GET_PLAYERS_REQUESTBYID";
 export const GET_PLAYERS_SUCCESSBYID = "GET_PLAYERS_SUCCESSBYID";
 export const GET_PLAYERS_FAILUREBYID = "GET_PLAYERS_FAILUREBYID";
